version: "3.9"

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-nicoruedaa/olmanager}/backend:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
      - ./assets:/assets

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-nicoruedaa/olmanager}/frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend