ALTER TABLE teams ADD COLUMN scrim_weekly_played INTEGER NOT NULL DEFAULT 0;
ALTER TABLE teams ADD COLUMN scrim_weekly_wins INTEGER NOT NULL DEFAULT 0;
ALTER TABLE teams ADD COLUMN scrim_weekly_losses INTEGER NOT NULL DEFAULT 0;
