import { readdirSync, writeFileSync } from "fs";
import { resolve } from "path";

const SPLASH_DIR = resolve("public/champion-splash");
const OUT_FILE = resolve("src/assets/champion-splash-list.ts");

const files = readdirSync(SPLASH_DIR)
  .filter((f) => f.endsWith(".webp"))
  .map((f) => f.replace(/\.webp$/, ""))
  .sort((a, b) => {
    const normalizedA = a.toLowerCase();
    const normalizedB = b.toLowerCase();

    if (normalizedA < normalizedB) return -1;
    if (normalizedA > normalizedB) return 1;
    if (a < b) return -1;
    if (a > b) return 1;
    return 0;
  });

const content = `// Generated by scripts/generate-splash-manifest.ts — do not edit manually
export const CHAMPION_SPLASH_LIST: string[] = ${JSON.stringify(files)};\n`;

writeFileSync(OUT_FILE, content);
console.log(`Generated champion splash manifest: ${files.length} entries → ${OUT_FILE}`);
