/// Legacy football foul/card system — removed in LoL migration.
/// In League of Legends, there are no fouls, penalties, or cards.
/// All match events are generated by the main simulation loop directly.

use rand::Rng;

use crate::types::Side;

#[allow(unused_variables)]
pub(super) fn maybe_foul<R: Rng>(
    ctx: &mut crate::engine::MatchContext,
    minute: u8,
    fouling_side: Side,
    fouled_snap: &crate::shared::PlayerSnap,
    fouler_snap: &crate::shared::PlayerSnap,
    zone: crate::types::Zone,
    rng: &mut R,
) {
    // No-op: fouls don't exist in League of Legends
}
